🧪 add failing test
IBM/py-to-proto pull request #60
Opened 2023-09-26 21:14 UTC by prashantgupta24

2023-09-27 20:37 UTC, prashantgupta24 commented on py_to_proto/converter_base.py
> +            name=f"{package}.{name.lower()}.proto",
We use the package name to construct the `full_name` here: https://github.com/IBM/py-to-proto/blob/main/py_to_proto/converter_base.py#L130. So ideally we want them to be the same

2023-09-27 22:02 UTC, gabe-l-hart requested changes
Two little NITs in the tests, but otherwise this looks like a simple elegant fix!

2023-09-27 22:02 UTC, gabe-l-hart commented on tests/test_dataclass_to_proto.py
> +        bar: str
```suggestion
    @dataclass
    class Foo:
        foo: int
        bar: str

```

2023-09-27 22:02 UTC, gabe-l-hart commented on tests/test_jtd_to_proto.py
> +    ### NOTE: This used to work before, but now raises an error
Rather than leaving this message, I think we should just update the serialized bytes above

2023-09-27 22:08 UTC, prashantgupta24 commented on tests/test_jtd_to_proto.py
> +    ### NOTE: This used to work before, but now raises an error
I tried doing that, but what content can we update it with? The proto file now cannot be named `outermessage.proto` since the name in the descriptor pool is going to be `package.name`.

2023-09-28 00:52 UTC, gabe-l-hart approved these changes
Looks good!

2023-09-28 00:52 UTC, merged